<?php
namespace Exceptions;

/**
 * Test class for FatalException.
 * Generated by PHPUnit on 2012-09-08 at 11:04:54.
 */
class FatalExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Exceptions\FatalException::__construct
     * @covers Exceptions\BaseException::is_fatal
     * @covers Exceptions\BaseException::set_fatal
     * @covers Exceptions\Errors\Error::is_fatal
     * @covers Exceptions\Errors\Error::set_fatal
     */
    public function test__construct()
    {
        // 1. Случай контейнер для исключения \Exception
        $exception = new \Exception('message', 123);

        $e = new FatalException($exception);

        $this->assertEquals($exception->getMessage(), $e->getMessage(), '$e->getMessage() failed');
        $this->assertEquals($exception->getCode(), $e->getCode(), '$e->getCode() failed');
        $this->assertEquals($exception->getFile(), $e->getFile(), '$e->getFile() failed');
        $this->assertEquals($exception->getLine(), $e->getLine(), '$e->getLine() failed');
        $this->assertTrue(($exception === $e->getPrevious()), '$e->getPrevious() failed');
        $this->assertTrue(($exception === $e->get_previous()), '$e->get_previous() failed');

        $this->assertTrue($e->is_fatal(), '$e->is_fatal() failed');
        $this->assertTrue($e->is_loggable(), '$e->is_loggable() failed');

        // 2. Случай контейнер для BaseExceptionI
        $exception = new LoggableException('message', 123);

        $e = new FatalException($exception);

        $this->assertEquals('', $e->getMessage(), '$e->getMessage() failed');
        $this->assertEquals(0, $e->getCode(), '$e->getCode() failed');
        $this->assertTrue(($exception === $e->getPrevious()), '$e->getPrevious() failed');
        $this->assertTrue(($exception === $e->get_previous()), '$e->get_previous() failed');

        $this->assertTrue($exception->is_fatal(), '$exception->is_fatal() failed');
        $this->assertTrue($exception->is_loggable(), '$exception->is_loggable() failed');

        $this->assertFalse($e->is_fatal(), '$e->is_fatal() failed');
        $this->assertTrue($e->is_loggable(), '$e->is_loggable() failed');

        // 3. Случай контейнер для BaseExceptionI, но используется класс ошибки
        $exception = new Errors\Error(1, 'message', __FILE__, __LINE__);

        $e = new FatalException($exception);

        $this->assertEquals('', $e->getMessage(), '$e->getMessage() failed');
        $this->assertEquals(0, $e->getCode(), '$e->getCode() failed');
        $this->assertTrue(($exception === $e->get_previous()), '$e->get_previous() failed');

        $this->assertTrue($exception->is_fatal(), '$exception->is_fatal() failed');
        $this->assertTrue($exception->is_loggable(), '$exception->is_loggable() failed');

        $this->assertFalse($e->is_fatal(), '$e->is_fatal() failed');
        $this->assertTrue($e->is_loggable(), '$e->is_loggable() failed');
    }
}

?>
